server:
  port: 80

spring:
  main:
    web-application-type: none
    allow-circular-references: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/xxl_job?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.example.demo.pojo   # ?????
  mapper-locations: classpath:/mapper/*.xml   #  mapper??
  configuration:
    map-underscore-to-camel-case: true  # ????

logging:
  file:
    name: log/log.log   # ????????????????
  level:
    root: info
    wuhobin: debug


